zentralopensource/zentral

- zentral/contrib/munki/osx_package/build.tmpl/root/usr/local/zentral/munki/zentral_postflight
no functionality changed in the zentral-specific munki postflight, just explanatory text to make some
method/function return values and trickier logic easier to follow
> add docstrings for return values, control flow comments

- tests/osquery/test_osquery_compliance_probe.py
- zentral/contrib/osquery/probes/osquery_compliance.py
osquery> select filename, key, value from preferences p, file f WHERE ((p.path = '/Library/Preferences/com.apple.loginwindow.plist')) and f.path = p.path;
Error: no such column: p.path
preferences no longer has `path` key. osquery uses `plist` now
> osquery now uses plist (compliance queries)

- zentral/contrib/osquery/linux_script/template.sh
During my testing i utilized docker instances running ubuntu 16.04, and 14.04 it would fail because it failed to set a MACHINE_ID.  
This patch adds support for docker containers to the linux script ( `template.sh` )
> add support for Docker containers

- conf/start/docker/prometheus/Dockerfile
Currently the docker-compose image does not pin the prometheus version.  The current `prometheus.yml` is not compatible with the prometheus version.  This PR fixes the problem and ensure that everything comes up when you execute the command `docker-compose up -d`.
> update prometheus.yml to support prometheus 2

- conf/mdm/docker/nginx/conf.d/zentral.conf
- conf/start/docker/nginx/conf.d/zentral.conf
- server/base/management/commands/build_custom_error_pages.py
- server/templates/custom_error_page.html
Add build_custom_error_pages management command to render correct html
error pages that can be used by the HTTP proxy, when the application is
failing.
Remove buggy nginx error_page docker configurations. The new pages are
not configured, because they need to be built before they can be used.
It could be done in the docker-entrypoint, but the web app start is
already slow enough. PRs welcomed!
> Better solution for custom error pages

- tests/inventory/test_clean_ip_address.py
- zentral/contrib/inventory/utils.py
- zentral/contrib/jamf/api_client.py
Apply the same normalization as the GenericIPAddressField with the
unpack_ipv4 option to avoid MTObject hash errors.
> Clean Jamf API client IP addresses

- zentral/contrib/munki/osx_package/build.tmpl/scripts/postinstall
- zentral/contrib/munki/osx_package/builder.py
- zentral/utils/osx_package.py
Remove existing pre/postflight setup during the enrollment, if the
package has a distributor, for example, if it is part of a Monolith
manifest.
> Clean munki enrollment if distributor

- README.md
- docs/deployment/zaio-setup.md
- mkdocs.yml
While perusing the Zentral docs (at https://zentral.readthedocs.io/en/latest/) I noticed that the 'Edit on GitHub' link 404's because it references https://github.com/zentralopensource/zentral/edit/**master**/docs/index.md but it seems that, at some point, the primary/default branch was changed from `master` to `main`.
This PR will fix the broken 'Edit on GitHub' URL in the docs, as well as swap-out a couple other refs to the `master` branch that exist in the repo.
> Swap primary branch refs from 'master' to 'main'

- zentral/contrib/munki/osx_package/build.tmpl/root/usr/local/zentral/munki/zentral_postflight
We set all three values from scutil to the same asset tag ID, but end users are free to change what they see in System Preferences -> Sharing, which modifies the value we had been getting from SysProfiler (ComputerName which is most closely associated with Apple Remote Desktop's need to name computers easily). I don't see a reason to retain it or the bonjour sharing name end users can alter, adding HostName as an extra label to associate with the computer also doesn't seem helpful. It wasn't straightforward to me and my unclassful python to pull from the ManagedInstallReport parsing happening elsewhere in postinstall, so I'm using the same way munki gets it - https://github.com/munki/munki/blob/7f736a4901397711e67cf6e9282be0194c59e9eb/code/client/munkilib/info.py#L658
comment explains …
> Use HostName instead of localhostname for definitive 'name', for display in events/machine inventory list

- zentral/contrib/monolith/views.py
- zentral/contrib/osquery/views/api.py
- zentral/contrib/osquery/views/osquery_file_carve_probe.py
- zentral/utils/storage.py
The background task to build the archive would start before the last
block was committed to the DB.
> Fix osquery file carving transaction race

- zentral/contrib/santa/views.py
After [a few years](https://github.com/google/santa/issues/155), santa (v1.17)[ is finally sending](https://github.com/google/santa/commit/c5a048f4d9d9a421417f72a11f90e1e40970ad6f) the correct `Content-Encoding` header 😉
> Accept updated content-encoding for santa

- zentral/contrib/inventory/forms.py
- zentral/contrib/inventory/models.py
The query that is exactly returning the current sources with apps in the
inventory is too slow. It needs to be optimized if possible. In the
meantime, we use the faster query to find all the inventory sources –
some of them without apps.
> Use faster DB query for apps search source field

- tests/santa/test_santa_api_views.py
- zentral/contrib/santa/views.py
We have observed that the client_mode key is sometimes missing in the
data posted by santa on the preflight endpoint.
> Fix for santa preflight missing "client_mode" err

- conf/mdm/docker/nginx/conf.d/zentral.conf
- conf/start/docker/nginx/conf.d/zentral.conf
- server/accounts/models.py
- server/accounts/urls.py
- server/server/urls.py
- server/templates/accounts/verify_u2f.html
Move users admin and authentication views under the same path prefix.
This is cleaner and can help with an eventual request rate limiting
configuration.
> Regroup accounts/ URLs

- server/realms/backends/ldap/__init__.py
- server/realms/backends/openidc/__init__.py
- server/realms/backends/saml/__init__.py
- tests/server_realms/test_realm_backends.py
- tests/utils/test_remove_null_character.py
- zentral/utils/json.py
A NULL char in the next URL could not be saved in the callback kwargs
attribute of the realm authentication session (NULL cannot be saved in a
jsonb postgres field).
The callback kwargs are sanitized now.
> Fix NULL char error in realms login

- zentral/contrib/munki/osx_package/build.tmpl/root/usr/local/zentral/munki/zentral_postflight
Do not upload unfinished reports. This could happen if the postflight is
called during a Munki run, like when it is installed by monolith.
> Fix munki postflight

- Dockerfile
Small Fix following on from https://github.com/zentralopensource/zentral/pull/171 which added PiP constraints and attempted to copy an additional file to the path of `.` sadly this is not supported and gives an error when trying to do the local docker-compose workflows. 
Error from linter. 
```
When using COPY with more than one source file, the destination must be a directory and end with a / or a \dockerfile-utils(23)
```
> [Build Fix]Update docker copy commands

- tests/events/test_serialization.py
- tests/inventory/test_machine_snapshot.py
- tests/inventory/utils.py
- tests/osquery/test_setup_distributed_queries.py
- zentral/contrib/inventory/models.py
- zentral/contrib/osquery/forms.py
- zentral/contrib/osquery/templates/osquery/query_detail.html
- zentral/core/events/base.py
- zentral/core/probes/base.py
First steps to speed up the event enrichment.
Use single DB query for all event machine info.
Use this query results for probe filtering and machine info serialization.
> Optimize machine info serialization for the events

- zentral/contrib/monolith/templates/monolith/manifest.html
> Remove configure monolith cache server link

- zentral/contrib/inventory/utils.py
Avoid using the storage that can be remote as backend for the
ZipArchive. This fixes a bug seen with S3 storage.
> Build the ZIP locally and pass it to the storage

- server/accounts/views/auth.py
An external link with RBAC was skipped if preceeded by another non-RBAC
link.
> Fix RBAC nginx bug

- server/accounts/events/__init__.py
The django logout callback is triggered even when no user is being
logged out.
> Fix 500 when multiple logouts

- tests/osquery/test_api_views.py
- zentral/contrib/osquery/serializers.py
GUI can be modified, but updates over the API still fail with the message referenced in the test. Also modified serializer as it has the same ceiling for interval values, feel free to cherrypick/drop if that's not appropriate
> bump api interval test to match change in #261

- docs/apps/inventory.md
- mkdocs.yml
- zentral/contrib/inventory/models.py
This is a small change to contrib/inventory/models.py which adds the "principal user" information to the serialized machine info tied to an event. I accomplished this using pre-existing patterns.
This change was necessary to allow a Slack bot to easily identify which user to notify about a Santa block event.
> Add principal_user to machine model

- docs/configuration/stores.md
- zentral/core/stores/backends/splunk.py
Empty by default. Can be used to authenticate with a proxy.
> Add Splunk HEC and search API extra headers

- tests/stores/test_splunk.py
- zentral/core/stores/backends/splunk.py
Do not use the reserved "index" field. Concatenate the index field with
the id field before sending the event to Splunk.
> Fix ZTL event index Splunk serialization

- tests/munki/test_managed_installs.py
- zentral/contrib/munki/utils.py
Do not trigger a reinstall event if the installed at datetime for the
managed install was not present in the DB.
> No reinstall event if installed at was None

- tests/monolith/test_munki_api_views.py
- zentral/contrib/monolith/models.py
- zentral/contrib/monolith/urls.py
- zentral/contrib/monolith/views.py
Add custom `zentral_monolith_shard` pkginfo key, with a value between 1
and 100 (defaults to 100 if absent). If present and less than 100, the
pkginfo will be included in the catalog, only if the shard value
calculated with the pkg name, version and machine serial number is
lower.
> Add monolith pkginfo shards

- zentral/core/stores/views.py
Fix CodeQL alerts by removing the attribute and method stubs in the base
event view mixin.
Document these required attributes and methodes. Also add docstrings for
the base event views.
> Avoid method conflict in event views inheritance

- zentral/contrib/inventory/views.py
- zentral/contrib/monolith/views.py
- zentral/contrib/puppet/views.py
- zentral/contrib/santa/views/setup.py
- zentral/contrib/wsone/views.py
Either use a string for permission_required, or explicitly override its
value in each view.
> Fix CodeQL conflicting values alerts on EventsMixin

- zentral/contrib/santa/templates/santa/target_detail.html
Hide empty values
Show separator if multiple targets with same identifier
> Fix santa certificate target view

- zentral/contrib/osquery/models.py
Explanatory text tweak to denote windows executables instead of just apps and pkgs
> wording tweak

- constraints.txt
- requirements.txt
- server/server/celery.py
To address CVE-2020-17495, we use django-celery-results v2.4.0 and
configure explicitly the storage of the tasks arguments.
> Upgrade django-celery-results to v2.4.0

- tests/inventory/test_macos_build_parser.py
- zentral/contrib/inventory/conf.py
- Nullify zero patch number for macOS >= 11
- Add support for 11.6.7 and 11.6.8
> Fix macOS build parser

- zentral/utils/gcs_storage.py
- zentral/utils/storage.py
This is a workaround, to be able to sign blob URLs without a credential
file/private key.
References:
https://github.com/jschneier/django-storages/issues/941
https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.generate_signed_url
> Add custom storage backend for GCS

- docs/apps/mdm.md
I think this is a requirement in order for you to sign your own APNS certs with a vendor cert? You have to be an approved MDM vendor. 
I was not able to get this to work otherwise. When I log into my apple developer account, I get no link to manage my certificates, as per the instructions.
> Specify dependency on apple enterprise developer program

- server/realms/utils.py
- tests/mdm/test_account_configuration_command.py
- tests/mdm/test_commands.py
- tests/mdm/test_custom_command.py
- tests/mdm/utils.py
- tests/server_realms/test_realm_utils.py
- zentral/contrib/mdm/commands/account_configuration.py
- zentral/contrib/mdm/commands/base.py
- zentral/contrib/mdm/commands/custom.py
- zentral/contrib/mdm/commands/declarative_management.py
- zentral/contrib/mdm/commands/utils.py
- zentral/contrib/mdm/migrations/0035_auto_20210530_0717.py
- zentral/contrib/mdm/models.py
- zentral/contrib/mdm/views/mdm.py
- Refactor the commands to be able to reschedule some of them when the device checks in with an "Idle" status.
- More MDM command tests.
- Rework the AccountConfiguration command.
> Reschedule some commmands with NotNow status

- tests/osquery/test_osquery_api.py
- zentral/contrib/osquery/views/utils.py
Better for the inventory compliance checks (OS query returns strings, but numbers are stored in our DB).
> Fix OS version nums type for Osquery

- tests/monolith/test_models.py
- tests/monolith/test_setup_views.py
- zentral/contrib/monolith/models.py
- zentral/contrib/monolith/templates/monolith/sub_manifest.html
- Display a red background for PkgInfoNames without active PkgInfos in sub manifests.
- Do not display the edit button for PkgInfoNames without active PkgInfos in sub manifests.
> Better handle inactive names in sub manifests

- tests/monolith/test_api_views.py
- zentral/contrib/monolith/api_urls.py
- zentral/contrib/monolith/api_views.py
- zentral/contrib/monolith/serializers.py
This only includes the base Manifest API as discussed. 
catalogs, sub_manifests, enrollment_packages, printers etc from the Manifest Model are not part of the presentation in this PR. 
Includes:
- 2 endpoints, list and details (CRUD) for the Monolith manifests
- Search by name and meta business unit id on the list endpoint.
> Add Monolith Manifest API (base implementation)

- server/server/urls.py
- tests/conf/base.json
- tests/osquery/test_osquery_api.py
- zentral/contrib/osquery/models.py
- zentral/contrib/osquery/public_urls.py
- zentral/contrib/osquery/public_views.py
- zentral/contrib/osquery/urls.py
- zentral/contrib/osquery/views/__init__.py
Following [URL prefix for agent views](https://zentral-pro.slab.com/public/posts/url-prefix-for-agent-views-mqpd51kg)
* Added new files for public endpoints and views.
* New configuration flag `mount_legacy_public_endpoints` for apps.
* New test for public urls `test_public_urls`
* Tests enabling/disabling `mount_legacy_public_endpoints`
TBD
* Extend strategy to Santa.
> Adding prefix (public) to osquery endpoints

- tests/osquery/test_osquery_api.py
Refer to:
https://github.com/zentralopensource/zentral/pull/635#pullrequestreview-1310332734
> fix: osquery public endpoint test was incorrect.

- docs/apps/mdm.md
- tests/mdm/test_mdm_views.py
- zentral/contrib/mdm/crypto.py
- zentral/contrib/mdm/payloads.py
- zentral/contrib/mdm/views/mdm.py
This allows the Zentral MDM to work behind all proxies or load balancers, even if they cannot be configured to pass the client certificate data.
> Add MDM request signature header verification

- docs/architecture/index.md
- docs/deployment/zaio-gcp.md
Looks like the paths for images should be relative instead of absolute despite having WARNINGS on the mkdocs logs.
Follow up of #671 
```logs
WARNING  -  Documentation file 'architecture/index.md' contains a link to '../images/architecture/key_components.svg' which is not found in the documentation files.
WARNING  -  Documentation file 'architecture/index.md' contains a link to '../images/architecture/modules.svg' which is not found in the documentation files.
WARNING  -  Documentation file 'deployment/zaio-gcp.md' contains a link to '../images/deployment/zaio-gcp/create_instance_top_form.png' which is not found in the documentation
files.
WARNING  -  Documentation file 'deployment/zaio-gcp.md' contains a link to '../images/deployment/zaio-gcp/select_image.png' which is not found in the …
```
> fix: Broken image links in documentation

- ee/zentral/contrib/intune/templates/intune/tenant_detail.html
- tests/intune/test_index_view.py
Displaying correct info when revealing secrets on tenant display template
> fix: get_client_secret vs client_secret on template

- zentral/contrib/mdm/api_views/artifacts.py
- zentral/contrib/mdm/api_views/blueprints.py
- zentral/contrib/mdm/artifacts.py
- zentral/contrib/mdm/serializers.py
The blueprint serialized artifacts must be updated after the artifacts, profiles, and blueprint artifacts are changed.
If changes occur concurrently, the serialized artifacts may be inconsistent, because of the transaction isolation in PostgreSQL: the blueprint is updated with the changes seen in the transaction, not the other transactions that might be currently open.
We use multiple transactions and locks on the blueprints to make sure all changes are seen before the serialized artifacts are updated.
> Fix MDM blueprint API concurrency issue

- tests/mdm/test_mdm_views.py
- zentral/contrib/mdm/declarations.py
- zentral/contrib/mdm/public_urls.py
- zentral/contrib/mdm/public_views/mdm.py
We do not rely on mTLS anymore for authentication. Instead, we use a signed token containing the required information to be able to serve the profile.
> Better MDM legacy profile download view

- zentral/contrib/mdm/models.py
iOS devices will reuse the same session in case of a SCEP verification error, which can lead to a device being unable to enroll, even after the SCEP verification issue has been solved.
Even without an expiry, the session can only be used once.
> Do not set an expiry on DEP enrollment sessions

- tests/mdm/test_api_filevault_configs_views.py
- tests/mdm/test_management_filevault_config.py
- zentral/contrib/mdm/api_views/filevault_configs.py
- zentral/contrib/mdm/models.py
- zentral/contrib/mdm/templates/mdm/filevaultconfig_detail.html
- zentral/contrib/mdm/templates/mdm/filevaultconfig_list.html
- zentral/contrib/mdm/views/management.py
… when the FileVaultConfig is used in a Blueprint.
> Protect FileVaultConfig from deletion

- tests/mdm/test_certificate_list_command.py
- tests/mdm/test_commands_scheduling.py
- tests/mdm/test_device_configured_command.py
- tests/mdm/test_device_information_command.py
- tests/mdm/test_installed_application_list_command.py
- tests/mdm/test_mdm_views.py
- tests/mdm/test_profile_list_command.py
- tests/mdm/test_security_info_command.py
- zentral/contrib/mdm/commands/scheduling.py
- Always send the DeviceConfigured command
- Send the base inventory commands (Device, Security info) even if there are no blueprints.
- Send the extra inventory commands (Certs, Profiles, Apps) after the device is configured.
> Better MDM commands schedule

- tests/mdm/test_artifacts.py
- zentral/contrib/mdm/artifacts.py
- zentral/contrib/mdm/declarations.py
Do not filter the artifacts in the dependency tree before calculating what is in scope and what to install.
> Fix MDM artifact dependencies

- docs/deployment/zaio-aws.md
> Update the AWS docs to use SSM for console access

- CHANGELOG.md
- tests/monolith/test_api_views.py
- tests/monolith/test_munki_api_views.py
- zentral/contrib/monolith/public_urls.py
- zentral/contrib/monolith/public_views.py
- zentral/contrib/monolith/urls.py
- zentral/contrib/monolith/utils.py
- zentral/contrib/monolith/views.py
Use the `/public` prefix for the Monolith views that need to be public.
> Separate Monolith public endpoints

- tests/munki/test_script_check_views.py
- zentral/contrib/munki/forms.py
- zentral/contrib/munki/templates/munki/scriptcheck_list.html
- zentral/contrib/munki/views.py
> feat: Script checks search

- zentral/contrib/osquery/templates/osquery/configuration_list.html
Changing `Feeds` for `Configurations` on Santa/Configurations empty listing.
> fix: Santa configuration list wrong placeholder

- tests/osquery/test_setup_enrollments.py
- zentral/contrib/osquery/releases.py
Fall back to proposing no Osquery release if GitHub cannot be reached.
> Fix Osquery enrollment GitHub errors

- zentral/contrib/inventory/cleanup.py
Certificates can be linked to profiles. We need to cleanup the profiles before, and make sure that we do not delete certificates linked to existing profiles.
> Fix inventory certificate cleanup

- zentral/contrib/mdm/management/commands/send_device_notification.py
- zentral/contrib/mdm/management/commands/sync_software_updates.py
- zentral/core/queues/backends/aws_sns_sqs/__init__.py
- zentral/core/queues/backends/aws_sns_sqs/consumer.py
- zentral/core/queues/backends/base.py
- zentral/core/queues/backends/google_pubsub/__init__.py
- zentral/core/queues/backends/kombu.py
Can be used to stop existing threads in the command line utilities.
Also reworked the graceful stop in the AWS queues to trigger the original signal handler. This is used when running in gunicorn.
> Add stop() method to queues

- constraints.txt
CVE-2023-52323. This is a snowflake connector dependency.
> Upgrade pycryptodomex to 3.19.1

- tests/inventory/test_macos_build_parser.py
- zentral/contrib/inventory/conf.py
This change fixes the automatic parsing of some of the latest macOS releases.
The impact is minimal, this is a simple fix.
> Add newest macOS builds

- zentral/contrib/mdm/schema_data/README.md
- zentral/contrib/mdm/schema_data/skipkeys.yaml
- zentral/contrib/mdm/skip_keys.py
- Update `skipkeys.yaml` to Release_iOS-17-4_macOS-14-4
- Use the `title` key instead of the `content` key in the form
> Update MDM ADE Skip Keys

- CHANGELOG.md
- tests/santa/test_santa_api_views.py
- tests/santa/test_setup_views.py
- zentral/contrib/santa/public_urls.py
- zentral/contrib/santa/public_views.py
- zentral/contrib/santa/utils.py
- The enrollment secret must be present as `Bearer` token in the `Zentral-Authorization` header.
- The existing URLs are deprecated and will be removed in the near future.
> Use header authentication for the Santa agent

- server/base/middlewares.py
- tests/server_base/test_index.py
Unnecessary. We do not want to support older browsers.
> Remove unsafe-inline fallback

- tests/mdm/test_setup_filevault_command.py
- zentral/contrib/mdm/commands/setup_filevault.py
When FV is configured after a device has enrolled, and the device is asleep, the command will fail with a NotNow status. It must be rescheduled when the device wakes up.
> Reschedule SetupFileVault cmds with NotNow status

- zentral/contrib/mdm/workers.py
This allows the process to exit gracefully. Otherwise, an event publishing thread might still be running, and the process would not be restarted by systemd for example.
> Stop event queues on APNS worker errors

- tests/inventory/test_metrics_views.py
- zentral/contrib/inventory/metrics_views.py
The minor and patch OS version in the database should default to 0, and 0 is a valid value for those 2 labels.
> Fix minor and patch OS versions metrics labels

- tests/santa/test_ballot_box.py
- zentral/contrib/santa/ballot_box.py
Make sure that not only a ballot from the same realm user is a match, but also a ballot from a different realm user with the same username. This avoids double votes in the case of 2 SAML apps with different scopes (All the employees for the portal, only the admins for the Zentral console) but from the same IdP, so with the same usernames.
> Ensure Santa ballot unicity across realms

- tests/santa/test_ballot_box.py
- zentral/contrib/santa/ballot_box.py
- zentral/contrib/santa/utils.py
The reset checks where not done per configuration, but globally.
> Fix Santa ballot box bug

- tests/santa/test_santa_api_views.py
- zentral/contrib/santa/public_views.py
This should fix the sync issue when a device is erased and enrols on the same configuration, with the same enrollment.
> Clean sync when no rule counts in Santa preflight

- tests/osquery/test_api_views.py
- zentral/contrib/osquery/api_views.py
Allow standard authentication on Osquery run export API endpoints to fix the UI.
> Fix Osquery run exports from UI

- CHANGELOG.md
- tests/mdm/test_artifacts.py
- tests/mdm/test_install_profile_command.py
- tests/mdm/test_remove_profile_command.py
- tests/mdm/test_workers.py
- zentral/contrib/mdm/artifacts.py
- zentral/contrib/mdm/commands/scheduling.py
- zentral/contrib/mdm/models.py
- zentral/contrib/mdm/workers.py
At the moment, the MDM agent and daemon do no retry the failed downloads of configuration profiles. This is problematic, especially when some payloads disrupt the network (Firewall config). The devices could be left in a state that requires a reboot to recover from. This is not good enough, especially during an MDM enrollment.
> Switch back to MDM command for legacy profiles

- constraints.txt
- zentral/contrib/santa/migrations/0037_configuration_banned_threshold_and_more.py
Different legacy bundle rules can cover the same binary. That could cause integrity error during the migration.
> Fix DB error during Santa bundle rule migration

- tests/mdm/test_api_declarations_views.py
- zentral/contrib/mdm/declarations/declaration.py
- zentral/contrib/mdm/serializers.py
This should make it easier when adding this to the Terraform provider. If the ServerToken can be automatically generated by the server, this could introduce drift.
We keep the option in the GUI.
> Make MDM declaration ServerToken mandatory in API

- zentral/contrib/mdm/models.py
Do not check if the blueprint artifacts are installed. Simply check that the blueprint contains no blueprint artifacts. The extra checks are not necessary, and cost a lot because the ORM query is not optimized.
> Simplier Blueprint deletion check

- CHANGELOG.md
- tests/mdm/test_dep.py
- tests/mdm/test_setup_dep_enrollment.py
- zentral/contrib/mdm/dep.py
- zentral/contrib/mdm/tasks.py
- zentral/contrib/mdm/views/dep_enrollments.py
When a DEP profile is assigned to a lot of devices, the profile update with ABM can take a long time. This commit moves the update to a background task.
We also only post an update when the DEP profile changes, and avoid posting an update when only DEP enrollment attributes that do not affect the profile are changed.
> Post the DEP profile updates in background task
