- zentral/core/actions/backends/freshdesk.py
"freshdesk": {
"backend": "zentral.core.actions.backends.freshdesk",
"subdomain": "subdomain",
"default_ticket_email": "default_mail@example.com",
"api_key": "xxxxx-api-key-xxxxx",
"password": "x"
},
name: Inventory group change freshdesk
metadata_filters:
- type: inventory_update
tags:
- group_change
actions:
freshdesk:
priority: urgent
email: mail@example.com
type: Support
tags:
- zentral
- api
- change
> add support for Freshdesk ticket system - v2 API

- basic-auth-use-info.md
- conf/basic_auth/docker/nginx/conf.d/zentral.conf
- conf/basic_auth/docker/nginx/extra/ReadMe.md
- conf/basic_auth/docker/nginx/extra/zentral.htpasswd
- docker-compose-basic-auth.yml
- zentral/contrib/osquery/osx_package/build.tmpl/scripts/postinstall
- zentral/contrib/osquery/osx_package/build.tmpl/scripts/preinstall
- zentral/contrib/santa/osx_package/build.tmpl/scripts/postinstall
- zentral/contrib/santa/osx_package/build.tmpl/scripts/preinstall
via docker-compose, use: `docker-compose --file
docker-compose-basic-auth.yml up -d`
> add basic-auth

- zentral/contrib/jamf/forms.py
Added a mask to the password input field for the JSS Instance Form so its not visible whilst typed.
> Added password mask for JSS password input field

- docker-compose.yml
Hi there,
Although it is a minor change, I made a fix according to the topic.
Thank you
> Since rabbitmq attr is defined twice in docker-compose.yml, I delete one.

- .github/workflows/tests.yml
This should make the tests run faster.
> Use BuildKit

- zentral/core/queues/backends/aws_sns_sqs/consumer.py
- zentral/core/queues/backends/aws_sns_sqs/sqs.py
Stop the ReceiveThread correctly, and before the other threads. Let the other threads finish their job.
> Fix AWS SNS/SQS queues graceful shutdown

- zentral/contrib/jamf/api_client.py
The RestAPIOperation are triggered by Zentral own processing of some
events, amplifying the number of events to process!
Proceed carefully if you want to enable it!
> Disable RestAPIOperation Jamf webhook by default

- zentral/contrib/monolith/forms.py
- zentral/contrib/monolith/templates/monolith/delete_manifest_catalog.html
- zentral/contrib/monolith/templates/monolith/manifest.html
- zentral/contrib/monolith/templates/monolith/manifest_catalog_form.html
- zentral/contrib/monolith/urls.py
- zentral/contrib/monolith/views.py
Fix typo in delete manifest catalog view
Add view to edit manifest catalogs tags
Avoid duplicated catalogs
Fixes #117
> Better monolith manifest catalogs forms

- tests/server_accounts/test_users_views.py
- zentral/contrib/jamf/api_client.py
- zentral/contrib/jamf/preprocessors/webhook.py
> Jamf webhook armour

- zentral/contrib/inventory/utils.py
- Redirect to first page if out of page range
- Redirect to machine view if only one result and free input filters
(computer name, serial number, principal user name) used
> Better inventory machine list views redirects

- zentral/contrib/inventory/utils.py
> Add pincipal user to inventory export

- zentral/contrib/monolith/forms.py
- zentral/contrib/monolith/templates/monolith/manifest.html
- zentral/contrib/monolith/templates/monolith/manifest_sub_manifest_form.html
- zentral/contrib/monolith/urls.py
- zentral/contrib/monolith/views.py
> Add monolith manifest sub manifests tagging view

- zentral/contrib/munki/osx_package/build.tmpl/root/usr/local/zentral/munki/zentral_postflight
Some keys in the Munki reports might be missing
> Fix Munki postflight report issue

- zentral/contrib/munki/osx_package/build.tmpl/root/usr/local/zentral/munki/zentral_postflight
> Use SC for logged in user in munki postflight

- tests/monolith/test_models.py
- zentral/contrib/monolith/models.py
Remove the duplicates caused by tag filtering
> Fix monolith manifest submanifests & catalogs

- zentral/conf/secrets.py
Secretmanager has been in GA since Q1 2020.
> Updated secretmanager to v1

- zentral/contrib/munki/views.py
These could help debug bursts of munki events
> Add report & event counts in munki postflight events

- docs/apps/santa.md
- tests/santa/test_api_views.py
- zentral/contrib/santa/serializers.py
> Add type and sha256 to Santa API rule error msg

- zentral/contrib/inventory/management/commands/cleanup_inventory_history.py
This is used as the default retention period in days for the
cleanup_inventory_history command.
> Add snapshot_retention_days inventory app setting

- zentral/contrib/inventory/templates/inventory/machine_detail.html
- zentral/contrib/inventory/views.py
- zentral/core/probes/views.py
- zentral/core/stores/__init__.py
- zentral/core/stores/backends/base.py
> 20210317 machine buttons

- tests/inventory/test_update_machine_tags.py
- zentral/contrib/inventory/api_urls.py
- zentral/contrib/inventory/api_views.py
- zentral/contrib/inventory/serializers.py
First implement a filter based on principal user unique id or principal
name.
> Add API for machine mass-tagging

- server/realms/templates/realms/realm_detail.html
> No realm group mapping grp link if not authzed

- zentral/contrib/monolith/templates/monolith/catalog_list.html
- zentral/contrib/monolith/views.py
> Hide archived monolith catalogs if auto mgmt

- zentral/contrib/inventory/utils.py
Avoid huge memory requirements on the client side.
> Use server-side cursors for apps exports

- zentral/contrib/inventory/utils.py
Use .jsonl as suggested on https://jsonlines.org/
> Change machine snapshot export file extension

- zentral/core/actions/backends/http_post.py
> Fix http_post action form bug

- server/accounts/management/commands/create_zentral_user.py
With this option, a password reset email will also be sent.
> Add send email opt to create_zentral_user command

- zentral/conf/secrets.py
> Fix log level of the config secret plugins

- zentral/contrib/osquery/osx_package/build.tmpl/root/Library/LaunchDaemons/pro.zentral.osqueryd.plist
- zentral/contrib/osquery/osx_package/build.tmpl/root/usr/local/zentral/osquery/flagfile.txt
- zentral/contrib/osquery/osx_package/build.tmpl/scripts/postinstall
- zentral/contrib/osquery/osx_package/build.tmpl/scripts/preinstall
- zentral/contrib/osquery/osx_package/builder.py
- zentral/utils/osx_package.py
Compatibility with osquery v5
Custom pro.zentral.osqueryd launchd daemon
Flag file
> Update osquery enrollment

- zentral/contrib/osquery/linux_script/template.sh
Use EC2 IMDSv2 for instance name discovery
Use arch to add the correct debian repository
Remove unnecessary use of cat
> Linux osquery enrollment fixes

- zentral/core/queues/backends/aws_sns_sqs/__init__.py
- zentral/core/queues/backends/aws_sns_sqs/consumer.py
- zentral/core/queues/backends/aws_sns_sqs/sns.py
- zentral/core/stores/backends/base.py
- zentral/core/stores/backends/http.py
Only works on AWS SNS/SQS queues, with the new ConcurrentConsumer.
> Add concurrent HTTP event store

- docs/configuration/stores.md
- server/accounts/events/__init__.py
- server/base/views.py
- zentral/contrib/inventory/views.py
- zentral/core/stores/__init__.py
- zentral/core/stores/backends/elasticsearch.py
- zentral/core/stores/backends/splunk.py
Fetch machine and probe events via the Splunk API
> Splunk as frontend store

- zentral/core/stores/backends/splunk.py
The event "index" needs to be reconstructed.
> Fix splunk bulk store

- zentral/contrib/inventory/templates/inventory/machine_profiles.html
Reordered columns and information
Better search
Add profile count
> Better machine profiles list

- constraints.txt
- requirements.txt
- requirements_aws.txt
> Bump celery & its dependencies versions

- conf/common/docker/scepserver/verify_zentral_csr.py
refactoring code with Dictionary Comprehension which is more pythonic, concise and efficient; how do you think this change which has practical value？
> refactoring code with Dictionary Comprehension

- docs/apps/inventory.md
- tests/inventory/test_metrics_views.py
- zentral/contrib/inventory/metrics_views.py
- zentral/contrib/inventory/utils.py
Add Debian packages
Add Windows programs
Add sources and bundle ids/names filters
> Update the inventory metrics

- tests/inventory/test_metrics_views.py
- zentral/contrib/inventory/metrics_views.py
- zentral/contrib/inventory/utils.py
slightly faster DB queries
renamed metrics with "_bucket" suffix
added active machines
> Better inventory metrics

- zentral/contrib/monolith/repository_backends/s3.py
Use a S3 API HEAD request to get the region of a Monolith repository S3
bucket. This operation doesn't require any permissions.
> Get monolith repo S3 bucket region without perms

- zentral/contrib/inventory/utils.py
- zentral/contrib/inventory/views.py
Also, better handle last seen value errors
> Set default inventory last seen to 7d

- docs/apps/inventory.md
The URL parameter to filter the source is `source_name`
> Fix inventory machine apps & snapshots export docs

- tests/santa/test_santa_events.py
- zentral/contrib/santa/events/__init__.py
> Get team ID from santa event payload if possible

- tests/osquery/test_osquery_api.py
- zentral/contrib/osquery/conf.py
- zentral/contrib/osquery/views/utils.py
Add registry query to get the update build revision (UBR)
> Better windows build version with osquery

- tests/inventory/test_compliance_checks_api.py
- zentral/contrib/inventory/serializers.py
Allow missing and empty string values
> Fix JMESPath API description attr

- tests/inventory/test_exports.py
- zentral/contrib/inventory/utils.py
Correctly use a named DB cursor.
> Fix inventory exports OOM error

- tests/osquery/test_setup_distributed_queries.py
- zentral/contrib/osquery/forms.py
- zentral/contrib/osquery/templates/osquery/distributedquerymachine_list.html
- zentral/contrib/osquery/views/distributed_queries.py
adds search by serial number and filter by error on the osquery run machines page.
> add search to distributed machine list

- zentral/contrib/mdm/commands/base.py
> Use binary fmt to store the MDM command results

- tests/mdm/test_management_enrolled_device.py
- tests/mdm/test_management_enrolled_user.py
- zentral/contrib/mdm/templates/mdm/enrolleddevice_detail.html
- zentral/contrib/mdm/templates/mdm/enrolleduser_detail.html
- zentral/contrib/mdm/templates/mdm/usercommand_list.html
- zentral/contrib/mdm/urls.py
- zentral/contrib/mdm/views/management.py
- Show RequestType for CustomCommand
- Last 10 user commands
- Add MDM user command list view
- Add user management views tests
> Better MDM device and user command lists

- tests/monolith/test_api_views.py
- tests/monolith/test_setup_views.py
- zentral/contrib/monolith/forms.py
- zentral/contrib/monolith/serializers.py
> Fix sharding for monolith default installs

- tests/osquery/test_terraform.py
- zentral/utils/terraform.py
Add special case for the boolean values
> Fix Terraform export StringMapAttr

- tests/santa/test_api_views.py
- tests/santa/test_serializers.py
- zentral/contrib/santa/serializers.py
> Fix ruleset API errors with SIGNINGID rules

- tests/mdm/test_dep.py
- zentral/contrib/mdm/dep.py
Do not rely on a second sync to update the device info since the updated records may not be immediately available.
> Update DEP device profile info using the DB

- tests/santa/test_rule_engine.py
- zentral/contrib/santa/forms.py
Apparently, some binaries have weird signing IDs!
Fix #788
> Update Santa signing ID check

- tests/jamf/test_jamf_setup_views.py
- zentral/contrib/jamf/templates/jamf/index.html
- zentral/contrib/jamf/urls.py
- zentral/contrib/jamf/views.py
Overview page for Jamf Module.
> feat: Jamf Overview page

- package-lock.json
- package.json
- zentral/contrib/mdm/templates/mdm/blueprint_detail.html
- zentral/contrib/mdm/templates/mdm/blueprint_list.html
- zentral/contrib/mdm/templates/mdm/otaenrollment_detail.html
- zentral/contrib/mdm/templates/mdm/pushcertificate_detail.html
> fix: Certificate details template certificate name

- zentral/contrib/mdm/templates/mdm/enrolleddevice_detail.html
Form was missing for Poke Button on devices.
> fix: MDM poke button/form

- server/templates/core/stores/events_form.html
Links are now closer to the refresh button.
> fix: Event search buttons wide appart

- server/static_src/scss/styles.scss
- server/templates/base.html
- server/templates/base_error.html
> fix: Zentral logo dark/light mode

- docs/deployment/docker-compose.md
- Add the `css` and `js` bundles step
- Use `docker compose` instead of `docker-compose`
> Update the docker compose docs

- server/static_src/scss/styles.scss
- zentral/contrib/inventory/templates/inventory/machine_list.html
* Dismiss close button styling on Alerts and menu mobile version
* Field errors alignments on form validation
* Inventory search button alignments when resizing window.
> fix: UI bugfixing

- zentral/contrib/mdm/schema_data/skipkeys.yaml
Apple has added two new keys:
EnableLockdownMode
Wallpaper
The rest of text changes are comments about the content
> Update the skipkeys to latest

- tests/mdm/test_security_info_command.py
- zentral/contrib/mdm/commands/security_info.py
Remove the recovery password associated with an EnrolledDevice if the SecurityResponse indicates that no firmware password or recovery lock are configured.
> Clear recovery password with SecurityInfo response

- tests/mdm/test_workers.py
- zentral/contrib/mdm/workers.py
- Use MDM user user_id in notification events
- Fix DB updates when notification failure
- Add tests
> Fix MDM APNS workers

- zentral/contrib/munki/osx_package/build.tmpl/root/usr/local/zentral/munki/zentral_postflight
- zentral/contrib/munki/osx_package/build.tmpl/root/usr/local/zentral/munki/zentral_preflight
Fix errors when _mbsetupuser is present
> Fix current user detection in Munki postflight

- server/base/management/commands/build_custom_error_pages.py
- server/templates/base_error.html
To make them work even with mTLS errors
> Use full URL for custom error page assets

- zentral/utils/osx_package.py
Default to universal, local root only, no javascript
> Fix Distribution packages

- tests/mdm/test_dep_enrollment_public_views.py
- tests/mdm/test_software_updates.py
- zentral/contrib/mdm/models.py
- zentral/contrib/mdm/public_views/dep.py
Do not require an update when the system is already up to date.
Impact is minimal, it is only a bug fix.
> Fix ADE forced software updates

- tests/santa/test_santa_api_views.py
- zentral/contrib/santa/public_views.py
See https://github.com/google/santa/pull/1275
> Add `sync_type` key in Santa preflight response

- server/server/settings.py
> base.json option to set session cookie SameSite

- server/server/settings.py
> Better CSRF cookie settings

- tests/santa/test_rule_engine.py
- tests/santa/test_setup_views.py
- zentral/contrib/santa/forms.py
- zentral/contrib/santa/models.py
- Relax Signing ID verification
- Fix Signing ID search
- Fix Team ID search
- Fix rule creation form
> Fix issues with uncommon Santa target IDs

- tests/inventory/test_apps_views.py
- tests/inventory/test_search_views.py
- zentral/contrib/inventory/forms.py
- zentral/contrib/inventory/utils.py
Remove the regex search and use a LIKE instead.
> Fix inventory search with bad regex

- zentral/core/compliance_checks/tools/mSCP/build_tf_script_checks.py
- Skip rules without `result`
- Skip rules without macOS versions
- Better errors display
> Fix `build_tf_script_checks.py`

- tests/santa/test_santa_api_views.py
- zentral/contrib/santa/public_views.py
The JSON key changed from `serial_num` to `serial_number`.
> Fix for the Santa 2024.6 serial number issue

- package-lock.json
See https://osv.dev/vulnerability/GHSA-4vvj-4cpr-p986 CVE-2024-43788
> Bump webpack to v5.94.0

- zentral/contrib/santa/forms.py
- zentral/contrib/santa/templates/santa/targets.html
Use the collected signing IDs, to find team IDs event when the app comes from the App Store.
> Fix the Santa TEAMID target search

- zentral/contrib/inventory/utils.py
Closed machine incidents belonging to open incidents must be ignored.
> Fix incident status in machine list

- tests/mdm/test_mdm_views.py
- tests/mdm/utils.py
- zentral/contrib/mdm/public_views/mdm.py
- zentral/contrib/mdm/templates/mdm/depenrollment_detail.html
Apply the MDM enrollment tags during first enrollment.
> Fix MDM enrollment initial tagging

- server/templates/registration/invitation_email.html
- server/templates/registration/login.html
- server/templates/registration/password_reset_email.html
- server/templates/registration/password_reset_subject.txt
- tests/server_accounts/test_password_reset.py
- tests/server_accounts/test_users_views.py
Tweaking expressions to be more in line with how other systems phrase things, feel free to cherry pick, glad to provide examples from other systems if that would be better proof-wise
> Rephrasing copy re: password resets

- docs/configuration/stores.md
Small PR - adjusts the `docs/configuration/stores.md` to point to the correct `schema.yml` file.
> Update schema reference

- docs/apps/mdm.md
> Add initial info about Blueprints

- tests/mdm/test_declarations_utils.py
- zentral/contrib/mdm/declarations/utils.py
The value is in days, not in seconds!
> Fix MDM artifact reinstall interval

- zentral/contrib/monolith/conf.py
- Only update the cache if DB request successsful
- Reload the cache if missing repo
> Better Monolith repositories cache

- tests/mdm/test_setup_filevault_command.py
- zentral/contrib/mdm/commands/setup_filevault.py
Schedule a delayed `SecurityInfo` command when a `SetupFileVault` command is acknowledged.
> Speed up FileVault PRK key escrow

- server/base/templatetags/ui_extras.py
- server/templates/_empty_results.html
- tests/santa/test_targets_views.py
- zentral/contrib/santa/forms.py
- zentral/contrib/santa/templates/santa/targets.html
Do not run a full Santa target search without filters in the Targets view.
> Make Santa target search filters mandatory

- server/templates/user_menu.html
- tests/conf/base.json
- tests/core_stores/test_api_store_views.py
- tests/core_stores/test_conf.py
- tests/core_stores/test_store_views.py
- zentral/core/stores/api_views.py
- zentral/core/stores/conf.py
- zentral/core/stores/models.py
- zentral/core/stores/templates/stores/index.html
- zentral/core/stores/templates/stores/store_detail.html
- zentral/core/stores/urls.py
- zentral/core/stores/views/__init__.py
- zentral/core/stores/views/stores.py
This is used in the SaaS to limit the number of event stores a customer can create. It might be useful somewhere else too!
> Stores updates

- tests/core_stores/test_api_store_views.py
- zentral/core/stores/api_views.py
Some queues backends might use the PK to identify the queue associated with a store. After a deletion, this PK must be preserved to be able to mark the queue as deleted.
> Fix store queue deletion because of missing PK
